name: vant-encapsulation-page
on: 
  push:
    branches:
      - master
jobs:
  build-and-deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
    uses: actions/checkout@v1

    - name: Build and Deploy
    uses: JamesIves/github-pages-deploy-action@releases/v2
    env:
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    BRANCH: page
    FOLDER: dist
    BUILD_SCRIPT: npm install && npm run build:es && npm run demo:build


