name: vant-encapsulation-page
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-deploy:
  runs-on: ubuntu-latest
  steps:

    - name: qwer630701
    uses: actions/checkout@v1

    - name: Build and Deploy
    uses: JamesIves/github-pages-deploy-action@releases/v2
    env:
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    BRANCH: page
    FOLDER: docs
    BUILD_SCRIPT: npm install && npm run build
