name: GitHub pages deploy

on: 
  push:
    branches:
      - main
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - uses: actions/cache@v2.1.6
        id: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Deps
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build
        
      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "dist/index.html"
          target: "dist/404.html"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: page
          folder: dist
